server:
  port: 10002
  servlet:
    context-path: /oauthdashboard

# sql database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_module?useSSL=false&tinyInt1isBit=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    org.springframework.web: info
    sun.rmi: info
    javax.management: info
    com.jasper: debug


